---
version: '3.7'

services:
  mariadb:
    image: "mariadb:11.1.2-jammy"
    env_file:
      - ./.env_db
    volumes:
      - db-volume:/var/lib/mysql
  dolibarr:
    build:
      context: .
    depends_on:
      - mariadb
    env_file:
      - ./.env_dolibarr
    volumes:
      - ./composer/:/composer/requirements/
      # - ./htdocs/:/var/www/html
  nginx:
    image: nginx:1.25.3
    ports:
      - '9000:80'
    depends_on:
      - dolibarr
    volumes:
      - ./htdocs:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db-volume: